spring.application.name=filmhub
spring.profiles.active=dev
server.servlet.context-path=/api
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
#Para codespaces:
#Cambiar para cada codespaces. Ejemplo:
#swagger.server.url=https://congenial-space-enigma-6x7r4w6gvr93j5x-8080.app.github.dev/api
#Por defecto
swagger.server.url=http://localhost:8080/api
server.port=8080