FROM mcr.microsoft.com/devcontainers/java:21

# Maven ya está incluido en la imagen base, no necesitamos instalarlo


# Copiar el proyecto
WORKDIR /workspace
COPY . .

# Exponer el puerto de la aplicación
EXPOSE 8090